/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.util;

public class Utils1 {
    public static String loud(String s) {
        return s.toUpperCase();
    }
}
